/**
 * HeartVerses: A collection of 50+ Quranic verses focused on hope, patience, and spiritual success.
 */

export const HEART_VERSES = [
  { id: 1, arabic: "إِنَّ مَعَ الْعُسْرِ يُسْرًا", english: "Indeed, with hardship [will be] ease.", reference: "94:6" },
  { id: 2, arabic: "لَا تَقْنَطُوا مِن رَّحْمَةِ اللَّهِ", english: "Do not despair of the mercy of Allah.", reference: "39:53" },
  { id: 3, arabic: "إِنَّ اللَّهَ مَعَ الصَّابِرِينَ", english: "Indeed, Allah is with the patient.", reference: "2:153" },
  { id: 4, arabic: "فَاصْبِرْ صَبْرًا جَمِيلًا", english: "So be patient with gracious patience.", reference: "70:5" },
  { id: 5, arabic: "وَمَن يَتَوَكَّلْ عَلَى اللَّهِ فَهُوَ حَسْبُهُ", english: "And whoever relies upon Allah - then He is sufficient for him.", reference: "65:3" },
  { id: 6, arabic: "أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ", english: "Verily, in the remembrance of Allah do hearts find rest.", reference: "13:28" },
  { id: 7, arabic: "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا", english: "Our Lord, let not our hearts deviate after You have guided us.", reference: "3:8" },
  { id: 8, arabic: "وَاصْبِرْ لِحُكْمِ رَبِّكَ فَإِنَّكَ بِأَعْيُنِنَا", english: "And be patient for the decision of your Lord, for indeed, you are in Our eyes.", reference: "52:48" },
  { id: 9, arabic: "إِنَّ رَبِّي قَرِيبٌ مُّجِيبٌ", english: "Indeed, my Lord is near and responsive.", reference: "11:61" },
  { id: 10, arabic: "وَقُل رَّبِّ زِدْنِي عِلْمًا", english: "And say, 'My Lord, increase me in knowledge.'", reference: "20:114" },
  { id: 11, arabic: "يُرِيدُ اللَّهُ بِكُمُ الْيُسْرَ وَلَا يُرِيدُ بِكُمُ الْعُسْرَ", english: "Allah intends for you ease and does not intend for you hardship.", reference: "2:185" },
  { id: 12, arabic: "لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا", english: "Allah does not charge a soul except [with that within] its capacity.", reference: "2:286" },
  { id: 13, arabic: "وَعَسَىٰ أَن تَكْرَهُوا شَيْئًا وَهُوَ خَيْرٌ لَّكُمْ", english: "But perhaps you hate a thing and it is good for you.", reference: "2:216" },
  { id: 14, arabic: "إِن يَعْلَمِ اللَّهُ فِي قُلُوبِكُمْ خَيْرًا يُؤْتِكُمْ خَيْرًا", english: "If Allah knows [any] good in your hearts, He will give you [something] better.", reference: "8:70" },
  { id: 15, arabic: "وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَىٰ", english: "And your Lord is going to give you, and you will be satisfied.", reference: "93:5" },
  { id: 16, arabic: "وَاللَّهُ يَعْلَمُ وَأَنتُمْ لَا تَعْلَمُونَ", english: "And Allah knows, while you know not.", reference: "2:216" },
  { id: 17, arabic: "إِنَّ اللَّهَ يُحِبُّ الْمُتَوَكِّلِينَ", english: "Indeed, Allah loves those who rely [upon Him].", reference: "3:159" },
  { id: 18, arabic: "فَإِنَّ مَعَ الْعُسْرِ يُسْرًا", english: "For indeed, with hardship [will be] ease.", reference: "94:5" },
  { id: 19, arabic: "وَقَالَ رَبُّكُمُ ادْعُونِي أَسْتَجِبْ لَكُمْ", english: "And your Lord says, 'Call upon Me; I will respond to you.'", reference: "40:60" },
  { id: 20, arabic: "إِنَّا لَا نُضِيعُ أَجْرَ مَنْ أَحْسَنَ عَمَلًا", english: "Indeed, We will not allow to be lost the reward of any who did well in deeds.", reference: "18:30" },
  { id: 21, arabic: "فَذَكِّرْ إِنَّمَا أَنتَ مُذَكِّرٌ", english: "So remind, [O Muhammad]; you are only a reminder.", reference: "88:21" },
  { id: 22, arabic: "وَاصْبِرْ فَإِنَّ اللَّهَ لَا يُضِيعُ أَجْرَ الْمُحْسِنِينَ", english: "And be patient, for indeed, Allah does not allow to be lost the reward of those who do good.", reference: "11:115" },
  { id: 23, arabic: "قُل لَّن يُصِيبَنَا إِلَّا مَا كَتَبَ اللَّهُ لَنَا", english: "Say, 'Never will we be struck except by what Allah has decreed for us.'", reference: "9:51" },
  { id: 24, arabic: "وَاتَّبِعْ مَا يُوحَىٰ إِلَيْكَ وَاصْبِرْ", english: "And follow what is revealed to you, [O Muhammad], and be patient.", reference: "10:109" },
  { id: 25, arabic: "إِنَّ رَحْمَتَ اللَّهِ قَرِيبٌ مِّنَ الْمُحْسِنِينَ", english: "Indeed, the mercy of Allah is near to the doers of good.", reference: "7:56" },
  { id: 26, arabic: "وَاللَّهُ مَعَ الصَّابِرِينَ", english: "And Allah is with the patient.", reference: "8:66" },
  { id: 27, arabic: "وَهُوَ مَعَكُمْ أَيْنَ مَا كُنتُمْ", english: "And He is with you wherever you are.", reference: "57:4" },
  { id: 28, arabic: "يَهْدِي اللَّهُ لِنُورِهِ مَن يَشَاءُ", english: "Allah guides to His light whom He wills.", reference: "24:35" },
  { id: 29, arabic: "إِنَّ اللَّهَ لَا يُغَيِّرُ مَا بِقَوْمٍ حَتَّىٰ يُغَيِّرُوا مَا بِأَنفُسِهِمْ", english: "Indeed, Allah will not change the condition of a people until they change what is in themselves.", reference: "13:11" },
  { id: 30, arabic: "رَبِّ اشْرَحْ لِي صَدْرِي", english: "My Lord, expand for me my breast [with assurance].", reference: "20:25" },
  { id: 31, arabic: "وَيَسِّرْ لِي أَمْرِي", english: "And ease for me my task.", reference: "20:26" },
  { id: 32, arabic: "وَاحْلُلْ عُقْدَةً مِّن لِّسَانِي", english: "And untie the knot from my tongue.", reference: "20:27" },
  { id: 33, arabic: "فَفِرُّوا إِلَى اللَّهِ", english: "So flee to Allah.", reference: "51:50" },
  { id: 34, arabic: "نَحْنُ أَقْرَبُ إِلَيْهِ مِنْ حَبْلِ الْوَرِيدِ", english: "We are closer to him than [his] jugular vein.", reference: "50:16" },
  { id: 35, arabic: "إِنَّ رَبِّي لَسَمِيعُ الدُّعَاءِ", english: "Indeed, my Lord is the Hearer of supplication.", reference: "14:39" },
  { id: 36, arabic: "وَاسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ", english: "And seek help through patience and prayer.", reference: "2:45" },
  { id: 37, arabic: "إِنَّ اللَّهَ كَانَ بِكُمْ رَحِيمًا", english: "Indeed, Allah is to you ever Merciful.", reference: "4:29" },
  { id: 38, arabic: "وَأَنَّ اللَّهَ مَعَ الْمُؤْمِنِينَ", english: "And that Allah is with the believers.", reference: "8:19" },
  { id: 39, arabic: "إِنَّ اللَّهَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ", english: "Indeed, Allah is over all things competent.", reference: "2:20" },
  { id: 40, arabic: "اللَّهُ وَلِيُّ الَّذِينَ آمَنُوا", english: "Allah is the ally of those who believe.", reference: "2:257" },
  { id: 41, arabic: "فَأَيْنَمَا تُوَلُّوا فَثَمَّ وَجْهُ اللَّهِ", english: "So wherever you [might] turn, there is the Face of Allah.", reference: "2:115" },
  { id: 42, arabic: "وَاللَّهُ يَهْدِي مَن يَشَاءُ إِلَىٰ صِرَاطٍ مُّسْتَقِيمٍ", english: "And Allah guides whom He wills to a straight path.", reference: "2:213" },
  { id: 43, arabic: "وَاللَّهُ يُحِبُّ الصَّابِرِينَ", english: "And Allah loves the patient.", reference: "3:146" },
  { id: 44, arabic: "وَاللَّهُ ذُو فَضْلٍ عَظِيمٍ", english: "And Allah is the possessor of great bounty.", reference: "3:174" },
  { id: 45, arabic: "يَا أَيُّهَا الَّذِينَ آمَنُوا اصْبِرُوا", english: "O you who have believed, persevere.", reference: "3:200" },
  { id: 46, arabic: "وَاللَّهُ يُحِبُّ الْمُحْسِنِينَ", english: "And Allah loves the doers of good.", reference: "5:93" },
  { id: 47, arabic: "لَّا إِلَٰهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ", english: "There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers.", reference: "21:87" },
  { id: 48, arabic: "رَبِّ لَا تَذَرْنِي فَرْدًا", english: "My Lord, do not leave me alone.", reference: "21:89" },
  { id: 49, arabic: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ", english: "[All] praise is [due] to Allah, Lord of the worlds.", reference: "1:2" },
  { id: 50, arabic: "أَمَّن يُجِيبُ الْمُضْطَرَّ إِذَا دَعَاهُ", english: "Is He [not best] who responds to the desperate one when he calls upon Him?", reference: "27:62" },
  { id: 51, arabic: "وَإِذَا سَأَلَكَ عِبَادِي عَنِّي فَإِنِّي قَرِيبٌ", english: "And when My servants ask you, [O Muhammad], concerning Me - indeed I am near.", reference: "2:186" }
];
